-- Connect as application user
ALTER SESSION SET CURRENT_SCHEMA = compliance_user;

-- ===================== COMPLIANCE SCHEMA =====================

-- COMPLIANCE_VIOLATIONS
CREATE TABLE compliance_user.COMPLIANCE_VIOLATIONS (
    VIOLATION_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOE_ID          VARCHAR2(50)   NOT NULL,
    EMPLOYEE_NAME   VARCHAR2(200)  NOT NULL,
    DEPARTMENT      VARCHAR2(100)  NOT NULL,
    VIOLATION_DATE  DATE           NOT NULL,
    VIOLATION_TYPE  VARCHAR2(100)  NOT NULL,
    SEVERITY        VARCHAR2(20)   NOT NULL CHECK (SEVERITY IN ('Low', 'Medium', 'High', 'Critical')),
    STATUS          VARCHAR2(30)   NOT NULL CHECK (STATUS IN ('Open', 'In Progress', 'Closed', 'Escalated')),
    CLOSURE_DATE    DATE,
    REGULATORY_BODY VARCHAR2(100),
    FINANCIAL_IMPACT NUMBER(15,2)  DEFAULT 0
);

-- AUDIT_FINDINGS
CREATE TABLE compliance_user.AUDIT_FINDINGS (
    FINDING_ID    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    AUDIT_TYPE    VARCHAR2(100) NOT NULL CHECK (AUDIT_TYPE IN ('Internal Audit', 'External Audit', 'Regulatory Inspection')),
    DEPARTMENT    VARCHAR2(100) NOT NULL,
    FINDING_DATE  DATE          NOT NULL,
    DESCRIPTION   VARCHAR2(4000),
    RISK_RATING   VARCHAR2(20)  NOT NULL CHECK (RISK_RATING IN ('Low', 'Medium', 'High')),
    STATUS        VARCHAR2(30)  NOT NULL CHECK (STATUS IN ('Open', 'In Progress', 'Closed', 'Escalated'))
);

-- CONTROL_MAPPINGS
CREATE TABLE compliance_user.CONTROL_MAPPINGS (
    CONTROL_ID             NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONTROL_NAME           VARCHAR2(200)  NOT NULL,
    CONTROL_OWNER_DEPT     VARCHAR2(100)  NOT NULL,
    COMPLIANCE_REQUIREMENT VARCHAR2(500)  NOT NULL,
    EFFECTIVE_DATE         DATE           NOT NULL,
    TEST_FREQUENCY         VARCHAR2(50)   NOT NULL CHECK (TEST_FREQUENCY IN ('Daily', 'Weekly', 'Monthly', 'Quarterly', 'Annually'))
);

-- ===================== RISK SCHEMA =====================

-- RISK_EVENTS
CREATE TABLE compliance_user.RISK_EVENTS (
    EVENT_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOE_ID            VARCHAR2(50)   NOT NULL,
    DEPARTMENT        VARCHAR2(100)  NOT NULL,
    EVENT_DATE        DATE           NOT NULL,
    RISK_CATEGORY     VARCHAR2(100)  NOT NULL CHECK (RISK_CATEGORY IN ('Operational', 'Credit', 'Market', 'Liquidity', 'Regulatory')),
    LOSS_AMOUNT       NUMBER(15,2)   DEFAULT 0,
    EVENT_DESCRIPTION VARCHAR2(4000)
);
